name: twitter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI Dependencies
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.0.5

  # Network & API
  http: ^1.1.0
  dio: ^5.3.2

  # File Handling
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  file_picker: ^6.1.1
  
  # Utility
  intl: ^0.18.1
  crypto: ^3.0.3
  shared_preferences: ^2.2.0
  cached_network_image: ^3.3.0

  # UI Enhancements
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/